export const LOGIN_NAV = "LOGIN_NAV";
export const HIDDE_LOGIN_NAV = "HIDDE_LOGIN_NAV";
export const HIDDE_REGISTER_FORM = "HIDDE_REGISTER_FORM";
export const SHOW_REGISTER_FORM = "SHOW_REGISTER_FORM";
export const WORKER_REGISTER_FORM = "WORKER_REGISTER_FORM";
export const WORKER_DAY_FORM = "WORKER_DAY_FORM";

export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const USER_SUCCESS = "USER_SUCCESS";

export const REGISTER_WORKER = "REGISTER_WORKER";
