/* eslint-disable react-hooks/exhaustive-deps */
import Head from "next/head";
import Navbar from "@/components/Navbar";
import { getUserData } from "@/store/actions/authAction";

import { useEffect } from "react";

import { Provider, useDispatch, useSelector } from "react-redux";
import { ToastContainer } from "react-toastify";

import { wrapper, store } from "../store/store";

import "@/styles/globals.css";
import "react-toastify/dist/ReactToastify.css";

function App({ Component, pageProps }) {
  const { isAuth } = useSelector((state) => state.authReducer);
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch(getUserData());
  }, [isAuth]);

  return (
    <>
      <Provider store={store}>
        <Head>
          <title>NominaApp</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/nominaApp.svg" />
        </Head>
        <Navbar />
        <Component {...pageProps} />
        <ToastContainer />
      </Provider>
    </>
  );
}

export default wrapper.withRedux(App);
